name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # Node.js 관련 설정
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci

      # .env 파일 설정
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      # Python 가상 환경 설정 및 종속성 설치 (PM2로 실행하지 않음)
      - name: Set up Python 3.12.6
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Set up Python virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Python dependencies
        run: |
          source venv/bin/activate
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Node.js 서버 실행 (pm2로 관리)
      - name: Start Node.js server
        run: |
          pm2 restart BackendAPI
